MotionPlanMatrix = [TimeSeries';...
                    x_result';...
                    y_result';...
                    theta_result';...
                    PFx_result';...
                    PFy_result';...
                    PHx_result';...
                    PHy_result';...
                    PFcenterX_result_world';...
                    PFcenterY_result_world';...
                    PHcenterX_result_world';...
                    PHcenterY_result_world';];